### ISSUE TITLE
Cattr desktop 3.0.0-RC10 can't send screenshots to server

### ISSUE THREAD

**Issue by lexcorp** [cattr-app/desktop-application#37]
Cattr desktop 3.0.0-RC10 can't send screenshots to server

_**[D] [2023-05-16T21:22:25.408Z] [TaskTracker] Interval captured by timer request
[D] [2023-05-16T21:22:25.435Z] [TaskTracker] Capturing interval: 2023-05-16T21:21:24.732Z ~ 2023-05-16T21:22:25.406Z (duration = 60)
[D] [2023-05-16T21:22:25.516Z] [Controller:Time] Created a new track for task (c53254fb-c9d3-45cf-a800-cec9f87e1524): 60
[D] [2023-05-16T21:22:25.516Z] [TaskTracker] Track time is updated (+60 ticks)
[D] [2023-05-16T21:22:26.169Z] [Screenshot] Captured in 651ms
[D] [2023-05-16T21:22:26.169Z] [TaskTracker] Screenshot captured
[W] [2023-05-16T21:22:26.178Z] [Controller:Time-Intervals] Backing up time interval request
[E] [2023-05-16T21:22:26.179Z] [Controller:Time-Intervals] (API500) Error during interval & screenshot push: Error: Unknown message
<BEGIN STACK TRACE>
    at Object.module.exports.pushTimeInterval (C:\Users\Sistemas\AppData\Local\Programs\Cattr\resources\app.asar\app\src\controller\time-intervals.js:227:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async TaskTracker.captureCurrentInterval (C:\Users\Sistemas\AppData\Local\Programs\Cattr\resources\app.asar\app\src\base\task-tracker.js:631:32)
<END STACK TRACE>
[E] [2023-05-16T21:22:26.180Z] [TaskTracker] (API500) Error occured during the interval submit: Error: Unknown message
<BEGIN STACK TRACE>
    at TaskTracker.captureCurrentInterval (C:\Users\Sistemas\AppData\Local\Programs\Cattr\resources\app.asar\app\src\base\task-tracker.js:684:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
<END STACK TRACE>**_

_**[D] [2023-05-16T21:25:27.181Z] [TaskTracker] Interval captured by timer request
[D] [2023-05-16T21:25:27.192Z] [TaskTracker] Capturing interval: 2023-05-16T21:24:27.625Z ~ 2023-05-16T21:25:27.179Z (duration = 60)
[D] [2023-05-16T21:25:27.384Z] [Controller:Time] Updated track for task (c53254fb-c9d3-45cf-a800-cec9f87e1524): 240s (delta = +60s)
[D] [2023-05-16T21:25:27.384Z] [TaskTracker] Track time is updated (+60 ticks)
[D] [2023-05-16T21:25:27.871Z] [Screenshot] Captured in 487ms
[D] [2023-05-16T21:25:27.871Z] [TaskTracker] Screenshot captured
[W] [2023-05-16T21:25:27.876Z] [Controller:Time-Intervals] Backing up time interval request
[E] [2023-05-16T21:25:27.876Z] [Controller:Time-Intervals] (API500) Error during interval & screenshot push: Error: Unknown message
<BEGIN STACK TRACE>
    at Object.module.exports.pushTimeInterval (C:\Users\Sistemas\AppData\Local\Programs\Cattr\resources\app.asar\app\src\controller\time-intervals.js:227:9)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async TaskTracker.captureCurrentInterval (C:\Users\Sistemas\AppData\Local\Programs\Cattr\resources\app.asar\app\src\base\task-tracker.js:631:32)
<END STACK TRACE>
[E] [2023-05-16T21:25:27.877Z] [TaskTracker] (API500) Error occured during the interval submit: Error: Unknown message
<BEGIN STACK TRACE>
    at TaskTracker.captureCurrentInterval (C:\Users\Sistemas\AppData\Local\Programs\Cattr\resources\app.asar\app\src\base\task-tracker.js:684:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
<END STACK TRACE>**_

**Comment by lexcorp** [comment]
Ok, Well, this is related to the user specified in the nginx.conf configuration file. Put the nginx user and immediately the cattr client started to send the captures correctly.

[D] [2023-05-16T21:56:43.219Z] [TaskTracker] Capturing interval: 2023-05-16T21:55:43.649Z ~ 2023-05-16T21:56:43.196Z (duration = 60)
[D] [2023-05-16T21:56:43.496Z] [Controller:Time] Updated track for task (c53254fb-c9d3-45cf-a800-cec9f87e1524): 538s (delta = +60s)
[D] [2023-05-16T21:56:43.496Z] [TaskTracker] Track time is updated (+60 ticks)
[D] [2023-05-16T21:56:44.100Z] [Screenshot] Captured in 604ms
[D] [2023-05-16T21:56:44.100Z] [TaskTracker] Screenshot captured
[D] [2023-05-16T21:56:44.225Z] [Controller:Time-Intervals] Interval was synced
